chore: allow pulling helmfile releases from new helmfile repository
mamezou-tech/setup-helmfile pull request #40
Opened 2022-06-29 19:54 UTC by philomory

Also bumps the default versions of all tools.

Uses the `semver-compare` library to check whether we are installing version 0.145.0 or later; if so, we use the new repository. Otherwise, we use the old repository.

2022-06-29 22:29 UTC, philomory commented
Ah, I realize the problem now: I forgot to include `dist/index.js` in the commit; which, I mean, it say _right there_ in the readme :facepalm:.

2022-06-29 22:39 UTC, kondoumh commented
Thank you for the pull request.
I saw the CI log. The HTTP status is 404 at the time of download.

```
##[debug]Failed to download from "https://github.com/helmfile/helmfile/releases/download/v0.145.0/helmfile_linux_amd64". Code(404) Message(Not Found)
(node:1609) UnhandledPromiseRejectionWarning: Error: Unexpected HTTP response: 404
    at /home/runner/work/setup-helmfile/setup-helmfile/dist/index.js:3831:[25](https://github.com/mamezou-tech/setup-helmfile/runs/7121662968?check_suite_focus=true#step:3:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/setup-helmfile/setup-helmfile/dist/index.js:3741:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

2022-06-29 22:50 UTC, kondoumh commented
I was able to download it from this URL with curl.

`https://github.com/helmfile/helmfile/releases/download/v0.145.0/helmfile_0.145.0_linux_amd64.tar.gz`

2022-06-29 23:49 UTC, kondoumh requested changes
The lack of arguments for `semvercompare` was the cause of the CI error.

2022-06-29 23:49 UTC, kondoumh commented on src/setup.js
> +  if (semvercompare(version.replace(/^v/,), "0.145.0") >= 0) {
The second argument is required. This shoud work.

`if (semvercompare(version.replace(/^v/, ''), "0.145.0") >= 0) {`

2022-06-30 01:13 UTC, kondoumh requested changes
Hmmm. Can you push `dist/index.js` as well?

2022-06-30 01:26 UTC, philomory commented
> Hmmm. Can you push `dist/index.js` as well?
Done. I don't think I will _ever_ learn to remember to do this 🤦‍♂️

2022-06-30 01:31 UTC, kondoumh approved these changes
LGTM

2022-06-30 01:32 UTC, merged